# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170813_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='Full_name',
        ),
    ]
