# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170813_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Full_name',
            field=models.CharField(max_length=200),
        ),
    ]
